### ISSUE TITLE
Naming pattern files creates error when run

### ISSUE THREAD

**Issue by jonathan-s** [getgrit/gritql#155] opened 2024-04-04 13:20 UTC
It appears that pattern markdown files can't start with a number, and can't contain a hyphen. If they do it creates an error when you try to run it.

**Comment by morgante** [comment] 2024-04-04 16:33
Yes this is by design.

**Comment by jonathan-s** [comment] 2024-04-04 17:33
@morgante May I suggest a more helpful error in that case? The error doesn't really indicate that it's because of the filename is named in a "faulty" way.

**Comment by morgante** [comment] 2024-04-04 17:40
Agreed. We just fixed this for yaml (https://github.com/getgrit/gritql/pull/151) but should also improve markdown.

**Comment by morgante** [comment] 2024-04-04 21:05
Fixed in https://github.com/getgrit/gritql/pull/157

**Closed by morgante** 2024-04-04 21:05 UTC
