### ISSUE TITLE
TypeScript grammar needs update

### ISSUE THREAD

**Issue by morgante** [getgrit/gritql#27] opened 2024-03-16 00:59 UTC
This valid TypeScript code is interpreted as an error node. Error recovery creates comments where none exist:

```
type RouteResponse = `${infer Key extends keyof RouteResponses}:${string}`
        ? RouteResponses[Key]
        : never;

Cypress.Commands.add('getRouteVariant', (routeVariant) =>
  cy
    .request<{
      preview: {
        body: RouteResponses[typeof routeVariant extends `${infer T}:${string}`
          ? T
          : never];
      };
    }>('GET', `http://localhost:3110/api/mock/variants/${routeVariant}`)
    .then((res) => res.body.preview.body),
);
```

**Comment by ilevyor** [comment] 2024-03-18 04:19
```
type RouteResponse = `${infer Key extends keyof RouteResponses}:${string}`
        ? RouteResponses[Key]
        : never;
```

looks wrong to me. I think the conditional type needs to be of the form: `T extends S ? U : V` but in this example the `T extends S` is actually a template literal type, so we actually have a conditional of the form `T ? U : V`.

https://www.typescriptlang.org/docs/handbook/2/conditional-types.html

The babel playground also recognizes the above as a parse error:

https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=PTAEBcE8AcFNQEoHsCu5YNgZ2kgdlvALygAGAJAN4CWeAZrAE6gDSskosAHungCZZQAa3ZI6iVOkw58hLAF8AXFSzhGtAObzSAKBCgDhwwH4JaDNlwFsAbTaQAunrBGji0HlgA3JgG4dzhAw8ACiXACGALbQADawAIygJAAiSBqcPLD8ggCCeNSR4TGgpngokQBGTKDuqup4Gv76UHBmUpayxKC0DMz2GbwCwqLiyObSVnKBBgCQMyZtFjLWWHbsTvpzM-6ePoy-QA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Ctypescript&prettier=false&targets=&version=7.24.0&externalPlugins=&assumptions=%7B%7D

**Comment by morgante** [comment] 2024-03-18 04:33
Yeah I actually can't get it to parse without errors in the TS playground.

@SimeonC can you confirm this is actually valid? What TypeScript version + config are you using?

**Comment by SimeonC** [comment] 2024-03-18 07:27
Ohh, sorry. Guess I simplified it down a bit too much unintentionally, that example is incorrect - see this one https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYQJ5igUwM7bgXzgDMoIQ4ByAGwgGMBDKgWlvS1woG4BYAKD+AA7GJihF6tTHABKEAK4jpOSIOw5EfOJQDmmGE2xyoAN0yoKALjgQARgCtMtGD15b2KtVdsOnLrXNU5G2xaKGAbTC97R2c+fD4+ABNHKnosOG0aG0YNVzhBehBlCSk0DBw8BE0tOBh0KVkFTAA1NOB6YTgAXjgAAwASBABrMwgiGXlFZQhVHHwLQewYMMFtfF6-GrqwBsnMJWwPTAAeABVGkThMAA8RQUS8C5a2jpgAPm7qmrhzvavbzD3PADBBCIiiOAAaTM-zuDzgI1QYwmTQOR2w80WyyEa16X2+cAA-CipocZmpsABtaGoAC6+O+VkEmFMUE2WiEIjEJRQAAt6EJ6DYqFIqnlvroYE9WmFXmcnrDAfDpS9hG8ABQMmqkJoy9rCKy-JoAGi1AEorMh+YLhScnmjyScjSI3m92TUAPQAKi9WrgXrgAAFGO08KwAHQgOhDbAAVTUKtlwj9AcDYDShTgOpEeteKY9WrkagAIvQYPRE-qYOrs88kzArJXXha4MYIMBEu6tJKAIJgYBKACOchwMGw6pbVoFBVtxw6qEptLdWt7-YAykEQMAxxPLdaZyLjt4Yovl+KaqvgAAZCD0B67vnToWH49OU-u+J5T+fvhldjYcNkDIEAOgecM70SdUKElJthAoY04BrPZc2EM1ujeapWHxcMsGHUdjjFAk4HKYxgEwAB3KxCKIuAbAgRJUEbPYHVmKltkwZFaxQ+AbjhYFBjBCFTkxBAlhWXE-RqYlTkkrQmRZURaS7AgPw1CgAHEAFFTngvpeRgGAwAsD0PRoBgqF5CAlgsABmABGOyAAYPXofsPSjWghg9YxVTHD1Bi43z1jNbCYF5QF1RrHA0K6D52HDOiGPDEiyPIhL6NQM1TV4M1OCAA

**Comment by SimeonC** [comment] 2024-03-18 07:32
Yea, the playground is super not happy with this syntax so I'll just copy paste what I have there to replicate the issue;

## GritQL
```gritql
engine marzano(0.1)
language js

file($name, $body) where {
    $name <: r"(:?.*?)?([^\.]+)\.([^\.]+)$"($_, $type, $ext) where {
        ! and {
            $type <: `d`,
            $ext <: `ts`
        },
        ! $type <: `config`
    },
    $body <: contains bubble comment() as $c where {
        or {
            $c <: contains r"(.*) prettierignore(.*)"($s,$e) => `$s prettier-ignore$e`,
            $c <: contains r"^\/\* (css|html|sql|js) \*\/$"($type) where {
                $type = uppercase($type)
            } => `/* $type */`,
            and {
                $c <: within statement_block($statements) where {
                    $statements <: []
                },
                maybe $c <: contains r"(.*) TODO(?: ?)(.*)"($s,$e) => `$s $e`
            },
            and {
                ! $c <: r"(?:\s|.)*\s@[a-zA-Z-]+(?:\s|.)*",
                ! $c <: r".*eslint-disable.*",
                ! $c <: r".*prettier-ignore.*",
                ! $c <: r"^\/\* (?:CSS|HTML|SQL|JS) \*\/$",
                $c => .
            }
        }
    }
}
```

## Typescript
```ts
import { Cypress } from 'local-cypress';

interface RouteResponses {
  'get-survey': object;
  response: object;
  unsubscribe: object;
}

declare global {
  namespace Cypress {
    type RouteVariant = `${keyof RouteResponses}:${string}`;
    type RouteResponse<TRoute extends RouteVariant> =
      TRoute extends `${infer Key extends keyof RouteResponses}:${string}`
        ? RouteResponses[Key]
        : never;
    interface Chainable {
      getRouteVariant<TRoute extends RouteVariant>(
        routeVariant: TRoute,
      ): Chainable<RouteResponse<TRoute>>;
      /**
       * @alias cy.mocksUseRouteVariant
       * @param routeVariant
       */
      useDataRouteVariant(routeVariant: RouteVariant): void;
      getApiRequests(): Chainable<any[]>;
      getApiSubmits(): Chainable<object[]>;
      getApiLoads(): Chainable<object[]>;
    }
  }
}

Cypress.Commands.add('getRouteVariant', (routeVariant) =>
  cy
    .request<{
      preview: {
        body: RouteResponses[typeof routeVariant extends `${infer T}:${string}`
          ? T
          : never];
      };
    }>('GET', `http://localhost:3110/api/mock/variants/${routeVariant}`)
    .then((res) => res.body.preview.body),
);
```

As an aside, the "Yellow Warning" will cover the bottom lines in the input/output instead of pushing them up so you can't read the bottom lines of the input/output.

**Comment by ilevyor** [comment] 2024-03-18 14:05
This problem is caused by tsx breaking the typescript parser, so now there are two parsers for typescript, to use the older typescript older parser you can specify the language and the flavor:
`language js (typescript)`

**Comment by ilevyor** [comment] 2024-03-18 14:45
documentation of deprecation: https://www.typescriptlang.org/docs/handbook/jsx.html

**Comment by SimeonC** [comment] 2024-03-19 02:56
@ilevyor I tried adding that but the issue still persists.

I'm not sure where you found that this is related to `tsx` as the file sample I put in doesn't contain any `tsx/jsx` code at all. It's just pure typescript.

Also, I couldn't find in the link you sent any kind of deprecation notice, are you sure the link is correct?

**Comment by ilevyor** [comment] 2024-03-19 17:52
Hmm, sorry you're right I am seeing the problem persist even with the typescript flavor enabled. The issue isn't that there is jsx, it's that type assertions are not valid in typescript that accepts jsx. eg:
`const myCanvas = <HTMLCanvasElement>document.getElementById("main_canvas");` would not be parsable in a jsx file (above is fixed by enabling the typescript flavor)
https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions

what's weird, is that when parsing your example file with the CLI I get error nodes using the tsx parser, and not the typescript parser, but when I try to parse using the rust bindings I get error nodes fro both parsers.

**Comment by SimeonC** [comment] 2024-03-19 22:27
Yes that kind of type assertion isn't supported in tsx as far as I know.

The feature I'm using here is [generic types](https://www.typescriptlang.org/docs/handbook/2/generics.html) and [conditional types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html) not exactly everyday usage 😂

I think this exact syntax is classified as advanced typescript and most people won't use so you won't find it in the docs and I don't actually know what the official name for this is just that it works!

The exact code in my example that causes the error can be toggled with this diff, which is valid typescript as you can see in my linked ts playground above.

Both are valid typescript 
```diff
- type RouteResponse = `${infer Key extends keyof RouteResponses}:${string}`
        ? RouteResponses[Key]
        : never;
+ type RouteResponse = `${infer Key}:${string}`
        ? RouteResponses[Key]
        : never;
```

**Comment by ilevyor** [comment] 2024-03-20 19:59
quick update, working on updating the ts/js grammar to support this. Seems most recent version of those grammars do support this, but ours is a little stale, requires a bit of effort, as we modify the grammars to support our use case.

**Comment by SimeonC** [comment] 2024-03-21 03:24
Cool, thanks for the update - I've just .gritignore'd the file for now as I don't use this frequently so it's not urgent/blocking me.

**Closed** 2024-03-25 15:36 UTC
