### ISSUE TITLE
@getgrit/bridge is missing from npm

### ISSUE THREAD

**Issue by transitive-bullshit** [getgrit/gritql#223] opened 2024-04-13 19:47 UTC
Following up on #214, I'd like to play around with the [wasm-bindings](https://github.com/getgrit/gritql/tree/main/crates/wasm-bindings), so I checked things out locally and followed the contributing guidelines, `cargo test --workspace` runs fine.

Do I need to also initialize the `npm` side of things? Running `npm i` or `yarn install` at the top-level complains that `@getgrit/bridge` doesn't exist.

I'm guessing this is some private, internal module you guys are using, but this was surprising to me as a new contributor coming from the JS/TS ecosystem where I always expect a top-level `package.json` install to work, especially if there are sub-packages like the `wasm-bindings` which may rely on the top-level `node_modules` due to how node.js import resolution works.

**Comment by morgante** [comment] 2024-04-13 19:51
Yeah we don't currently publish any npm packages from this repo. If we release a JavaScript SDK, we'll be sure to add a root `package.json`.

**Comment by morgante** [comment] 2024-04-14 19:05
Closing this as a duplicate of https://github.com/getgrit/gritql/issues/214.

**Closed by morgante** 2024-04-14 19:05 UTC
